//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Entity Developer tool using EF Core template.
// -----------------------------------------------------------------------------
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace VMS.Requisitions.Querying.Entities
{
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class ApprovalProcess {

        public ApprovalProcess()
        {
            this.Approvals = new List<Approval>();
            OnCreated();
        }

        public virtual int EntityId
        {
            get;
            set;
        }

        public virtual int EntityTpCd
        {
            get;
            set;
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual IList<Approval> Approvals
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
