//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Entity Developer tool using EF Core template.
// -----------------------------------------------------------------------------
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace VMS.Requisitions.Querying.Entities
{
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class CustomField {

        public CustomField()
        {
            this.IsActive = true;
            this.SequenceNumber = 0;
            this.CustomFields_x_LinkedFldId = new List<CustomField>();
            this.CustomValues = new List<CustomValue>();
            OnCreated();
        }

        public virtual int EnitityTypeId
        {
            get;
            set;
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual bool IsActive
        {
            get;
            set;
        }

        public virtual string Label
        {
            get;
            set;
        }

        public virtual int OrganizationId
        {
            get;
            set;
        }

        public virtual int SequenceNumber
        {
            get;
            set;
        }

        public virtual CustomField CustomField_x_LinkedFldId
        {
            get;
            set;
        }

        public virtual IList<CustomField> CustomFields_x_LinkedFldId
        {
            get;
            set;
        }

        public virtual IList<CustomValue> CustomValues
        {
            get;
            set;
        }

        public virtual Organization Organization
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
