//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Entity Developer tool using EF Core template.
// -----------------------------------------------------------------------------
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace VMS.Requisitions.Querying.Entities
{
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class RequisitionSkill {

        public RequisitionSkill()
        {
            OnCreated();
        }

        public virtual System.Nullable<int> DurationTypeId
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> DurationValue
        {
            get;
            set;
        }

        public virtual System.Nullable<int> ExpertiseRatingId
        {
            get;
            set;
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual string Name
        {
            get;
            set;
        }

        public virtual int SequenceNumber
        {
            get;
            set;
        }

        public virtual int SkillsetTypeId
        {
            get;
            set;
        }

        public virtual int SkillTypeId
        {
            get;
            set;
        }

        public virtual ExpertiseRating ExpertiseRating
        {
            get;
            set;
        }

        public virtual Requisition Requisition
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
