//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Entity Developer tool using EF Core template.
// -----------------------------------------------------------------------------
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace VMS.Requisitions.Querying.Entities
{
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class RequisitionContact {

        public RequisitionContact()
        {
            OnCreated();
        }

        public virtual RequisitionContactRole ContactRoleId
        {
            get;
            set;
        }

        public virtual string EmailAddress
        {
            get;
            set;
        }

        public virtual string FirstName
        {
            get;
            set;
        }

        public virtual string LastName
        {
            get;
            set;
        }

        public virtual string MiddleInitial
        {
            get;
            set;
        }

        public virtual int RequisitionId
        {
            get;
            set;
        }

        public virtual int UserId
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          RequisitionContact toCompare = obj as RequisitionContact;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.RequisitionId, toCompare.RequisitionId))
            return false;
          if (!Object.Equals(this.ContactRoleId, toCompare.ContactRoleId))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + RequisitionId.GetHashCode();
          hashCode = (hashCode * 7) + ContactRoleId.GetHashCode();
          return hashCode;
        }
        
        #endregion
    }

}
