//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Entity Developer tool using EF Core template.
// -----------------------------------------------------------------------------
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace VMS.Requisitions.Querying.Entities
{
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class Requisition {

        public Requisition()
        {
            this.IsSalariedContractor = false;
            this.IsSowRequisition = false;
            this.NotToExceedRatePeriodId = 1;
            this.UseNotToExceed = false;
            this.Candidates = new List<Candidate>();
            this.CostCenters = new List<RequisitionCostCenter>();
            this.GeneralLedgers = new List<RequisitionGeneralLedger>();
            this.Projects = new List<RequisitionProject>();
            this.ReqBudgetDetails = new List<RequisitionBudgetDetail>();
            this.REQQSTNs = new List<RequisitionQuestion>();
            this.REQSKLSTs = new List<RequisitionSkill>();
            this.RequisitionComplianceInfos = new List<RequisitionComplianceInfo>();
            this.RequisitionContacts = new List<RequisitionContact>();
            OnCreated();
        }

        public virtual string AccountInfo
        {
            get;
            set;
        }

        public virtual string AlternateEmail
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> BillFromRate
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> BillToRate
        {
            get;
            set;
        }

        public virtual string Characteristics
        {
            get;
            set;
        }

        public virtual System.Nullable<int> ContractTierId
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> CreatedDate
        {
            get;
            set;
        }

        public virtual System.Nullable<int> DaysPerWeek
        {
            get;
            set;
        }

        public virtual string DepartmentName
        {
            get;
            set;
        }

        public virtual string Description
        {
            get;
            set;
        }

        public virtual System.Nullable<int> DurationTypeId
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> DurationValue
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> EndDate
        {
            get;
            set;
        }

        public virtual int FormatTypeId
        {
            get;
            set;
        }

        public virtual string HoursPerDay
        {
            get;
            set;
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual string InternalNumber
        {
            get;
            set;
        }

        public virtual bool IsSalariedContractor
        {
            get;
            set;
        }

        public virtual bool IsSowRequisition
        {
            get;
            set;
        }

        public virtual System.Nullable<bool> IsTemplate
        {
            get;
            set;
        }

        public virtual System.Nullable<int> LocationId
        {
            get;
            set;
        }

        public virtual System.Nullable<int> MaximumSubmittalsByVendor
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> MaxPayRate
        {
            get;
            set;
        }

        public virtual System.Nullable<int> MaxPayRatePeriodTypeId
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> MaxRate
        {
            get;
            set;
        }

        public virtual System.Nullable<decimal> NotToExceedRate
        {
            get;
            set;
        }

        public virtual int NotToExceedRatePeriodId
        {
            get;
            set;
        }

        public virtual int NumberOfFilled
        {
            get;
            set;
        }

        public virtual int NumberOfOpenings
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> OpenUntil
        {
            get;
            set;
        }

        public virtual int OrganizationId
        {
            get;
            set;
        }

        public virtual string ProjectName
        {
            get;
            set;
        }

        public virtual string RateInformationText
        {
            get;
            set;
        }

        public virtual System.Nullable<int> RequisitionCitizenStatusId
        {
            get;
            set;
        }

        public virtual System.Nullable<int> RequisitionClassId
        {
            get;
            set;
        }

        public virtual System.Nullable<int> RequisitionPriorityId
        {
            get;
            set;
        }

        public virtual System.Nullable<int> RequisitionStatusId
        {
            get;
            set;
        }

        public virtual string ShortDescription
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> StartDate
        {
            get;
            set;
        }

        public virtual string Title
        {
            get;
            set;
        }

        public virtual bool UseNotToExceed
        {
            get;
            set;
        }

        public virtual ActiveCandidatesCount ActiveCandidates
        {
            get;
            set;
        }

        public virtual AttachmentsCount Attachments
        {
            get;
            set;
        }

        public virtual IList<Candidate> Candidates
        {
            get;
            set;
        }

        public virtual ClientTier ContractTier
        {
            get;
            set;
        }

        public virtual IList<RequisitionCostCenter> CostCenters
        {
            get;
            set;
        }

        public virtual IList<RequisitionGeneralLedger> GeneralLedgers
        {
            get;
            set;
        }

        public virtual Location Location
        {
            get;
            set;
        }

        public virtual Organization Organization
        {
            get;
            set;
        }

        public virtual OrganizationDetail OrganizationDetail
        {
            get;
            set;
        }

        public virtual IList<RequisitionProject> Projects
        {
            get;
            set;
        }

        public virtual ReportsToContact ReportsToContact
        {
            get;
            set;
        }

        public virtual IList<RequisitionBudgetDetail> ReqBudgetDetails
        {
            get;
            set;
        }

        public virtual RequisitionFinancialDetail ReqFinancialDetail
        {
            get;
            set;
        }

        public virtual IList<RequisitionQuestion> REQQSTNs
        {
            get;
            set;
        }

        public virtual IList<RequisitionSkill> REQSKLSTs
        {
            get;
            set;
        }

        public virtual RequisitionClass RequisitionClass
        {
            get;
            set;
        }

        public virtual IList<RequisitionComplianceInfo> RequisitionComplianceInfos
        {
            get;
            set;
        }

        public virtual IList<RequisitionContact> RequisitionContacts
        {
            get;
            set;
        }

        public virtual StatusDescription StatusDescription
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
