//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Entity Developer tool using EF Core template.
// -----------------------------------------------------------------------------
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace VMS.Requisitions.Querying.Entities
{
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class StatusDescription {

        public StatusDescription()
        {
            OnCreated();
        }

        public virtual string Description1
        {
            get;
            set;
        }

        public virtual string Description2
        {
            get;
            set;
        }

        public virtual string Description3
        {
            get;
            set;
        }

        public virtual string Description4
        {
            get;
            set;
        }

        public virtual string Description5
        {
            get;
            set;
        }

        public virtual string Description6
        {
            get;
            set;
        }

        public virtual string Description7
        {
            get;
            set;
        }

        public virtual string Description8
        {
            get;
            set;
        }

        public virtual int RequisitionStatusId
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
